GET http://localhost:3000/medicalAppointments/search/Doe HTTP/1.1

###

GET http://localhost:3000/medicalAppointments HTTP/1.1

###

GET http://localhost:3000/medicalAppointments/2 HTTP/1.1

###
POST http://localhost:3000/medicalAppointments HTTP/1.1
Content-Type: application/json

{
    "patientName": "Angelo Gomez",
    "doctorName": "Dr. Smith",
    "date": "2024-05-26",
    "time": "02:00 PM",
    "reason": "Chequeo anual, descarte de enfermedades"
}

###

PUT http://localhost:3000/medicalAppointments/11 HTTP/1.1
Content-Type: application/json

{
    "patientName": "Angelo Gomez Tapia",
    "doctorName": "Dr. Shcaneyer",
    "date": "2024-05-26",
    "time": "02:00 PM",
    "reason": "Chequeo anual, descarte de enfermedades"
}

###

DELETE http://localhost:3000/medicalAppointments/11 HTTP/1.1
